-- MySQL Script generated by MySQL Workbench
-- ter 07 jun 2022 20:38:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @NUMERO = 0;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `funcodigo` DOUBLE NOT NULL,
  `funnome` VARCHAR(45) NOT NULL,
  `funidade` INT NOT NULL,
  `funfuncao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`funcodigo`),
  UNIQUE INDEX `funcodigo_UNIQUE` (`funcodigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dependentes` (
  `dencodigo` INT NOT NULL,
  `denfuncodigo` DOUBLE NOT NULL,
  `dennome` VARCHAR(45) NOT NULL,
  `dengrauparente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dencodigo`, `denfuncodigo`),
  INDEX `fk_dependentes_funcionarios_idx` (`denfuncodigo` ASC) VISIBLE,
  CONSTRAINT `fk_dependentes_funcionarios`
    FOREIGN KEY (`denfuncodigo`)
    REFERENCES `mydb`.`funcionarios` (`funcodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE TRIGGER funcionarios_BEFORE_DELETE BEFORE DELETE ON funcionarios FOR EACH ROW
BEGIN
	delete from dependentes d WHERE d.denfuncodigo = @NUMERO;
END$$


DELIMITER ;

-- INSERTS
insert into funcionarios values(
1,"Elsa de Arendelle",24,"Rainha"),
(2,"Anna de Arendelle",21,"Rainha Substituta"),
(3,"Merida de Burrock",19,"Arqueira"),
(4,"Miranda Casssandra",32,"Rainha dos Pebleus");

insert into dependentes values(
1,1,"olfa","Boneco de Neve"),
(2,1,"Swem","Rena Falante"),
(3,2,"Mordu","Urso Bravo"),
(4,2,"Rei Angus","pai rei"),
(5,3,"Tempestade","Dragao treinado"),
(6,3,"Rei Soluço","Marido Destreinado");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
